## Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
spec:
  selector:
    matchLabels:
      app: flaresolverr
  replicas: 1
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      containers:
      - name: flaresolverr
        image: ghcr.io/flaresolverr/flaresolverr:latest
        ports:
        - containerPort: 8191
          name: http-8191
#        volumeMounts:
#        - name: config
#          mountPath: "/config"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
#      volumes:
#      - name: config
#        persistentVolumeClaim:
#          claimName: sonarr-config
