## Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app: sonarr
  serviceName: "sonarr"
  replicas: 1
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name: sonarr
        image: lscr.io/linuxserver/sonarr:latest
        ports:
        - containerPort: 8989
          name: http-8989
        volumeMounts:
        - name: config
          mountPath: "/config"
        - name: library
          mountPath: /media/library
        - name: remote
          mountPath: "/media/remote"
        - name: shows
          mountPath: "/media/local/shows"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: sonarr-config
      - name: library
        persistentVolumeClaim:
          claimName: mediaserver-library
      - name: shows
        persistentVolumeClaim:
          claimName: mediaserver-shows
      - name: remote
        persistentVolumeClaim:
          claimName: mediaserver-remote


## Volumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: mediaserver
  labels:
    name: sonarr-config
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-perpetual
  resources:
    requests:
      storage: 8Gi
---
