## Service
---
apiVersion: v1
kind: Service
metadata:
   name: zurg
   labels:
     app.kubernetes.io/name: zurg
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 80
    targetPort: 9999
  selector:
    app.kubernetes.io/name: zurg