---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: riven
  name: riven
spec:
  selector:
    matchLabels:
      app: riven
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: riven
    spec:
      containers:
        - name: riven
          env:
            - name: RIVEN_SYMLINK_RCLONE_PATH
              value: "/media/remote/__all__/"
            - name: RIVEN_SYMLINK_LIBRARY_PATH
              value: "/media/local/"
            - name: RIVEN_DATABASE_HOST
              value: postgresql+psycopg2://postgres:postgres@riven-db/riven
            - name: RIVEN_FORCE_ENV
              value: "true"
            - name: PGID
              value: "911"
            - name: PUID
              value: "911"
            - name: TZ
              value: America/Detroit
          image: spoked/riven:latest
          readinessProbe:
            tcpSocket:
              port: backend-http
            #httpGet:
            #  path: /
            #  port: backend-http
            periodSeconds: 30
            timeoutSeconds: 10
          livenessProbe:
            tcpSocket:
              port: backend-http
            failureThreshold: 10
            periodSeconds: 30
            timeoutSeconds: 10
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "4000m"
          ports:
            - name: backend-http
              containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /riven/data
            - name: remote
              mountPath: /media/remote
            - name: metadata
              mountPath: /media/local
      restartPolicy: Always
      volumes:
        - name: remote
          persistentVolumeClaim:
            claimName: remote-media
        - name: metadata
          persistentVolumeClaim:
            claimName: metadata
          #nfs:
          #  path: /exports/
          #  server: metadata-server.streaming.k8s
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi