---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: riven
  annotations:
    polaris.fairwinds.com/tagNotSpecified-exempt: true  # Latest tag is desired here
  name: riven
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: riven
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: riven
    spec:
      containers:
        - name: riven
          env:
            - name: RIVEN_SYMLINK_RCLONE_PATH
              value: "/media/remote/__all__/"
            - name: RIVEN_SYMLINK_LIBRARY_PATH
              value: "/media/local/"
            - name: RIVEN_DATABASE_HOST
              value: postgresql+psycopg2://postgres:postgres@riven-db/riven
            - name: RIVEN_FORCE_ENV
              value: "true"
            - name: PGID
              value: "911"
            - name: PUID
              value: "911"
            - name: TZ
              value: America/Detroit
          image: spoked/riven:latest
          readinessProbe:
            tcpSocket:
              port: backend-http
            #httpGet:
            #  path: /
            #  port: backend-http
            periodSeconds: 30
            timeoutSeconds: 10
          livenessProbe:
            tcpSocket:
              port: backend-http
            failureThreshold: 10
            periodSeconds: 30
            timeoutSeconds: 10
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "250m"
          securityContext:
            allowPrivilegeEscalation: false
            runasNonRoot: true
          ports:
            - name: backend-http
              containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /riven/data
            - name: remotemedia
              mountPath: /media/remote
            - name: metadata
              mountPath: /media/metadata
      restartPolicy: Always
      volumes:
        - name: remotemedia
          persistentVolumeClaim:
            claimName: remotemedia
        - name: metadata
          persistentVolumeClaim:
            claimName: metadata
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi