## StatefulSets
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: riven-db
  name: riven-db
spec:
  selector:
    matchLabels:
      app: riven-db
  template:
    metadata:
      labels:
        app: riven-db
    spec:
      containers:
        - name: riven-db
          image: postgres:17.0
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_DB
              value: riven
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_SHARED_BUFFERS
              value: "512MB"                # 25% of 2GB
            - name: POSTGRES_WORK_MEM
              value: "4MB"                  # Low per-connection memory
            - name: POSTGRES_MAINTENANCE_WORK_MEM
              value: "128MB"                # Maintenance tasks like VACUUM
            - name: POSTGRES_MAX_CONNECTIONS
              value: "50"                   # Limited connections to prevent memory overuse
            - name: POSTGRES_EFFECTIVE_CACHE_SIZE
              value: "1.5GB"                # Around 75% of total memory
          livenessProbe:
            exec:
              command:
                - pg_isready
                - "-U"
                - postgres
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: data
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi