## Shared Volume for storing thumbnails, posters, trailers, and symlinks
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streaming-metadata
  labels:
    name: metadata
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: [ ReadWriteMany ]
  storageClassName: longhorn-perpetual
  resources:
    requests:
      storage: 64Gi
    matchLabels:
      name: metadata