apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metadata-server
  labels:
    name: metadata-server
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-perpetual
  resources:
    requests:
      storage: 32Gi