## Shared Volume for storing thumbnails, posters, trailers, and symlinks
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metadata
  labels:
    name: metadata
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: [ ReadWriteMany ]
  storageClassName: longhorn-shared
  resources:
    requests:
      storage: 32Gi